### PR TITLE
Feature/ci-support-gulp-removal

### PR DESCRIPTION
**Pull request by maxrolon**
@wturnerharris Adding you here for visibility.

This branch focuses on providing CI support (making the user prompts optional) in addition to removing gulp. I'm going to do a little more testing before merging in.

### CODE REVIEW

**Comment by wturnerharris** [comment]
@maxrolon - this makes way more sense now.

**Comment by wturnerharris** [comment]
@montalvomiguelo - we replaced `gulp` in this build due to outdated dependencies and vulnerabilities. It's mainly for copy and HMR. Can you test this on an upcoming project?

**Comment by montalvomiguelo** [comment]
Changes on locale files are not being watched during development. 



cc. @maxrolon @wturnerharris

**Comment by khoipro** [comment]
### Test Case

@wturnerharris I created a test case with one of existing project.

Project: Zupa Noma

Markup:

- Edit `modules/404/404.liquid` => **PASSED**, copied to `dist/`
- Edit `modules/header/header.section.liquid` => **PASSED**, copied to `dist/`

Javascript

- Edit `src/assets/js/main.js` => **PASSED**, copied to assets bundle and load console.log.
- Edit` src/modules/header/header.js` => **PASSED**, copied to assets bundle and load console.log.

CSS

- Edit `/src/modules/header/header.css` => **PASSED**, copied to assets bundle and load console.log.

JSON

- Edit `src/config/lib/featured-blog.json` => **PASSED**, copied to `/dist/config/settings_schema.json`
- Edit `src/locales/en.default.json` => **FAILED**, no copy. Must re-run a script `npm run start` to begin over.

**Comment by wturnerharris** [comment]
@khoipro - thanks for the test case. Looks similar to @montalvomiguelo issue above.

@montalvomiguelo - Oliver had another test case, can you add here for everyone?

**Comment by khoipro** [comment]
### Test Case with WordPress

Project: Cornell Tech

@wturnerharris 

**Processing time:**

Not sure it's because it's too much code or something else.

```
webpack building...
webpack built d3ea34af3556c8826f11 in 18033ms
webpack building...
webpack built 9407e286820343aa68f5 in 19182ms
webpack building...
webpack built 20b5e767d9900fff9b87 in 15742ms
webpack building...
webpack built 5a746f353fcf19c94aa9 in 17687ms
webpack building...
webpack built be39f53205bc4b56a546 in 20356ms
```

**Style changes:**

- Make a change to _modules/hero-video/hero-video.css_ => **PASSED**, the web browser was changed. 
- Make a change to _src/css/base/containers.css_ => **PASSED**, the web browser was changed. 

**Javascript changes:**

- Edit _src/js/main.js_ => **PASSED**, the console log output in web browser inspector.
- Edit _modules/hero-video/hero-video.js_ => **PASSED**, the console log output in web browser inspector.

**Markup changes:**

- Edit _modules/hero-video/hero-video.php_ => **FAILED** to instant change a web browser, you must manual refresh a web browser.

**Conclusion:**

It seems this patch working as normally, except the process time is too long at this moment.

**Pull request merged**
